"""Add estimated hours to tasks

Revision ID: 1c97b17a7c37
Revises: 584222d28338
Create Date: 2026-10-08 16:01:12.626824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1c97b17a7c37'
down_revision: Union[str, Sequence[str], None] = '584222d28338'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('estimated_hours', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'estimated_hours')
    # ### end Alembic commands ###
